### ISSUE TITLE
login via gitlab button not showing up

### ISSUE THREAD

**Issue by hdeadman** [gabrie-allaigre/sonar-auth-gitlab-plugin#19]
Sorry to create an issue for something that is really a question. I followed the instructions and don't have any errors, this plugin is loaded, but I am not seeing a button to login on my sonarqube login page. My server base url is https but the server is actually listening on http (it is behind an ssl proxy). Is this plugin responsible for adding the login with gitlab button to the sonar login page?

Thanks.

**Comment by gabrie-allaigre** [comment]
Hi,
What is Sonar version ?

**Comment by hdeadman** [comment]
6.7.0.33306 - Community Edition

**Comment by gabrie-allaigre** [comment]
Have you set, applicationId, secret and set enabled plugin in sonar administration ?
Verify if you are a ad-blocker ?

**Comment by hdeadman** [comment]
Yes, I believe I followed all the instructions you provided and filled out everything within SonarQube and Gitlab. I don't have any ad blockers in my browser. I don't understand what code is responsible for putting that button on the login form. Is that Sonar doing it? This plugin? Where is the login with gitlab image coming from?

**Comment by fhaertig** [comment]
The same is happening for me. I'm trying to set this up with the gitlab.com cloud version and SonarQube 7.0 and plugin version 1.3.1. I followed the instructions, ssl is working, but the plugin seems to fail. The following exception is thrown when trying to access oauth2/callback/gitlab:

```
2018.02.23 10:39:53 ERROR web[AWG91P4PKuz10lT9AAMu][o.s.s.a.AuthenticationError] Failed to retrieve IdentityProvider for key 'gitlab'
java.lang.IllegalArgumentException: Identity provider gitlab does not exist or is not enabled
	at org.sonar.server.authentication.IdentityProviderRepository.getEnabledByKey(IdentityProviderRepository.java:54)
	at org.sonar.server.authentication.AuthenticationFilter.resolveProviderOrHandleResponse(AuthenticationFilter.java:56)
	at org.sonar.server.authentication.OAuth2CallbackFilter.doFilter(OAuth2CallbackFilter.java:66)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:72)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Is it a version conflict?

**Comment by tomkuba** [comment]
I have same error in log. Version 6.7.1 does not show login button. Version 5.6.7 works.

**Comment by gabrie-allaigre** [comment]
Hi,
Plugin work with SonarQube 6.7.1. Verify all parameters. 
For SonarQube 7.0, I don't know, I'm not tested.

**Comment by tomkuba** [comment]
Thanks for confirmation. There must be something wrong in my setup - Gitlab8+nginx+docker+selfsigned certificates. I'll investigate more.

**Comment by gabrie-allaigre** [comment]
Hi,
I just tested version 7.0
There is a strange behavior with the secret field.
You must press the 2 save buttons of the fields.

![image](https://user-images.githubusercontent.com/14994297/38024351-08c69194-3285-11e8-8922-a46342bacbe5.png)

![image](https://user-images.githubusercontent.com/14994297/38024372-1bd67722-3285-11e8-9df9-4f043f69db14.png)

**Comment by gabrie-allaigre** [comment]
Issue in SonarQube is here https://jira.sonarsource.com/browse/SONAR-10039

**Comment by hdeadman** [comment]
I am closing this issue since it is working for me now.
