### ISSUE TITLE
Redirect after login ignores port

### ISSUE THREAD

**Issue by stepman0** [gabrie-allaigre/sonar-auth-gitlab-plugin#25]
I have a sonarqube setup with nginx reverse proxy (for https) on port 9001, i.e. https://server:9001/ 

In gitlab, I configured the application (as user) with the correct url: https://server:9001/oauth2/callback/gitlab

In Sonarqube, I configured the base URL (https://server:9001) and the Gitlab-Settings (Gitlab Url, Application Id, Secrect)

Login with gitlab works, but the redirection to Sonarqube brings my browser to https://server/ instead of https://server:9001/

Going to https://server:9001/ manually afterwards works and I am signed in. This seems to be a problem with redirection not authentification.

Any advice?

Versions:
Sonarqube Version 7.1 (build 11001)
Sonar-auth-gitlab-plugin: Version 1.3.2
Gitlab CE 10.8.2

**Comment by antonioseric** [comment]
I am haveing same issue. :(

**Comment by gabrie-allaigre** [comment]
Hi,
@stepman0 @antonioseric can you give me the first url calling gitlab?

**Comment by antonioseric** [comment]
Link on gitlab btn is  
`https://server:9000/sessions/init/gitlab?return_to=%2F`  
and then redirect to gitlab server
`https://server:9090/oauth/authorize?client_id=xxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fserver%3A9000%2Foauth2%2Fcallback%2Fgitlab&response_type=code&scope=api`

**Comment by gabrie-allaigre** [comment]
`server:9000` is sonar server
`server:9090` is gitlab server

Callback url is correct, `https%3A%2F%2Fserver%3A9000%2Foauth2%2Fcallback%2Fgitlab` 

What is a next url after accepted in gitlab ?

**Comment by antonioseric** [comment]
next url is 
`https://server:9000/oauth2/callback/gitlab?code=57939376c0cb2fa4bdd8a5b65a70c3f99b436ad35d7ff04918592764f8650260`
and after that  
`http://server/sessions/unauthorized` without port number

**Comment by gabrie-allaigre** [comment]
The last redirection is not create by plugin. I don't know port is missing.

**Comment by antonioseric** [comment]
in cookies i saw this: `Cookie: AUTH-PARAMS=%7B%22return_to%22%3A%22%2F%22%7D;`

Do you have solution for this issue?

**Comment by muralito** [comment]
I have the same setup, and it seems the problem is with the last step, when Sonarqube try to validate the oauth token sent by the browser.

I had put the "mygitlab" certificate in the java trustore, but i'm not sure if sonarqube is using it (i think the trustore is in use, because the same trustore is used by sonarqube to connect to the marketplace)

The sonarqube web server log says:

2018.10.19 15:53:10 ERROR web[AWaNp+DuUGSuznqbAAAn][o.s.s.a.AuthenticationError] Fail to callback authentication with 'gitlab'
com.github.scribejava.core.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service: https://mygitlab/oauth/token
	at com.github.scribejava.core.model.OAuthRequest.send(OAuthRequest.java:39)
	at com.github.scribejava.core.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:36)
	at com.talanlabs.sonar.plugins.gitlab.auth.GitLabIdentityProvider.callback(GitLabIdentityProvider.java:102)
	at org.sonar.server.authentication.OAuth2CallbackFilter.handleOAuth2Provider(OAuth2CallbackFilter.java:97)
	at org.sonar.server.authentication.OAuth2CallbackFilter.handleProvider(OAuth2CallbackFilter.java:77)
	at org.sonar.server.authentication.OAuth2CallbackFilter.doFilter(OAuth2CallbackFilter.java:70)
	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
	at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.github.scribejava.core.model.OAuthRequest.addBody(OAuthRequest.java:82)
	at com.github.scribejava.core.model.OAuthRequest.doSend(OAuthRequest.java:55)
	at com.github.scribejava.core.model.OAuthRequest.send(OAuthRequest.java:37)
	... 48 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 63 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 69 common frames omitted

**Comment by muralito** [comment]
I forget to add, that for this tests, i was accessing sonarqube by http in port 9000, and not using the ssl setup. 

When I try to use both sonarqube and gitlab by https, seem that the oauth process is ignoring the https setup, sending a http://server:9000 link to gitlab, and the gitlab server refuses that url and doesn't generate the token, and the process stops in a previous step.

**Comment by KristijanL** [comment]
Hi,

i have the same issue only on SQ 7.5, but on SQ 6.7 is working fine.

GitLab 11.1.4 (63daf37)
Sonar-auth-gitlab-plugin Version 1.3.2
Sonarqube Version : 6.7.6.38781 - NO ISSUE
Sonarqube Version : 7.5.0.20543 - SAME ISSUE

the propery "GitLab Ignore Certificate" on 7.X is not working properly ( or working as intended ), i had to add my root CA in java cacerts to get it working on 7.X version.

**Comment by Maniblue** [comment]
@KristijanL how to add root CA in Java cacerts?
If possible provide few steps

**Comment by Maniblue** [comment]
@KristijanL Is it necessary to download Sonar-auth-gitlab-plugin Version 1.3.2?

**Comment by Maniblue** [comment]
@KristijanL Is this correct URL https://server:9001/oauth2/callback/gitlab? For sonarqube community version?

**Comment by muralito** [comment]
> 

No. Gitlab authentication is now (dont remember when, but i think it was in sonarqube 8) integrated in sonarqube, so no need for plugin.

**Comment by muralito** [comment]
> @KristijanL Is this correct URL https://server:9001/oauth2/callback/gitlab? For sonarqube community version?

if you are now installing sonarqube, you probably aren't using this plugin, so this is not the best place to ask. I would ask in the sonarsource community forum https://community.sonarsource.com/

**Comment by muralito** [comment]
> 



> @KristijanL how to add root CA in Java cacerts?
> If possible provide few steps
The best way to do that depends on the linux distribution you are using. Better ask on your distribution specific forum.
