### ISSUE TITLE
Must provide a valid url as callback. GitLab does not support OOB

### ISSUE THREAD

**Issue by avirtual** [gabrie-allaigre/sonar-auth-gitlab-plugin#34]
When clicking on the 'Log in with Gitlab' i am being redirected to `https://mysonar/sessions/unauthorized`
The logs show `2019.08.26 14:36:32 WARN  web[AWzORS4Xd5cSiI5hAAGU][o.s.s.a.AuthenticationError] Fail to initialize authentication with provider 'gitlab'
java.lang.IllegalArgumentException: Must provide a valid url as callback. GitLab does not support OOB
        at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:73)
        at com.github.scribejava.core.utils.Preconditions.checkValidUrl(Preconditions.java:51)
        at com.talanlabs.sonar.plugins.gitlab.auth.GitLabOAuthApi.getAuthorizationUrl(GitLabOAuthApi.java:57)
`
A gitlab application was configured with the callback set to https://mysonar/oauth2/callback/gitlab
The gitlab plugin in sonar was configured with the correct gitlab url, plus application id and secret given by gitlab.

I am out of ideas and the log doesn't tell me much.

**Comment by lexxxel** [comment]
I do have the same issue
